service: echo-telegram-bot
frameworkVersion: '2'

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  telegram-webhook:
    handler: handler.telegramWebhook
    timeout: 28
    events:
      - http:
          path: /telegram/webhook/{token}
          method: post
  telegram:
    handler: handler.telegram
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline
